### PR TITLE
Move substitute_yaml_values to test utilities and add unit test.

### PR DESCRIPTION
**Pull request by KBaichoo**
Signed-off-by: Kevin Baichoo <kbaichoo@google.com>

### CODE REVIEW

**Comment by jiajunye** [comment]
Am I supposed to be the reviewer, instead of the assignee? @KBaichoo

**Comment by KBaichoo** [comment]
yes, sorry for envoy we assign the reviewer via `/assign` e.g. the assignee looks at the code this is due to codeowners pulling in a bunch of folks who aren't necessarily reviewing the code.

Do you have a repokitteh tag to assign reviewer? Otherwise I can't add reviewer.

**Comment by jiajunye** [comment]
No worries. We just set the `waiting-for-review` label. (I just did that for you)

**Comment by KBaichoo** [comment]
/review @jiajunye 

should add you as reviewer. Unfortunately I can't add labels.

**Comment by mum4k** [comment]
Thanks @KBaichoo and @jiajunye for sorting out the reviewer assignment. @jiajunye please assign this to me once you're done with the review.

**Comment by jiajunye** [comment]
LGTM

**Review by mum4k — CHANGES_REQUESTED** [review]
This is a nice improvement, thank you.

Would you be able to look into the CI failures?

**Review by mum4k — APPROVED** [review]

**Pull request merged**
