### PR TITLE
Update Envoy to c55b207 (Mar 14, 2022)

### PR DESCRIPTION
**Pull request by eric846**
- New `.bazelrc` from Envoy
- Add placeholder `Envoy::Server::Instance` where the `ClusterManagerFactory` constructor (inherited from Envoy's `Envoy::Upstream::ProdClusterManagerFactory`) now requires one.
- Run `pytest` with `--assert=plain` to work around `TypeError: required field "lineno" missing from alias` which started happening for unknown reasons in this PR in local `ci/do_ci.sh test` RBE runs, including on a clean machine. Opened #819.

Signed-off-by: eric846 <56563761+eric846@users.noreply.github.com>

### CODE REVIEW

**Comment by mum4k** [comment]
@qqustc please review and assign back to me once done.

**Review by qqustc — APPROVED** [review]
LGTM

**Review by mum4k — APPROVED** [review]

**Comment by mum4k** [comment]
The integration tests can no longer execute due to https://github.com/envoyproxy/nighthawk/issues/820.

Patched this PR in and executed the tests locally to confirm they are passing. Going to merge as is.

**Pull request merged**
