### PR TITLE
Update Envoy to c5833f2 (May 17th 2021)

### PR DESCRIPTION
**Pull request by qqustc**
- Sync .bazelrc
- Update bazel/repositories.bzl
- disable test_gcc due to #686 

Signed-off-by: qqustc@gmail.com <qqin@google.com>

### CODE REVIEW

**Comment by mum4k** [comment]
Since `test_gcc` is failing due to #686, can we disable it in this PR until we resolve the issue? We should also revert the `2xlarge` change.

Additionally, please document all the changes done here in the PR description.

**Comment by qqustc** [comment]
> Since `test_gcc` is failing due to #686, can we disable it in this PR until we resolve the issue? We should also revert the `2xlarge` change.
> 
> Additionally, please document all the changes done here in the PR description.

Done, thanks!

**Review by mum4k — APPROVED** [review]

**Pull request merged**
