### PR TITLE
A collection of fixes that simplify import of Nighthawk into Google.

### PR DESCRIPTION
**Pull request by mum4k**
Done here:

- removing comments next to the licenses in BUILD files, since that triggers a style warning.
- exporting the main LICENSES file.
- fixing bad include prefix and import of Nighthawk's distributor API.
- removing implicit conversions of strings to booleans.

### CODE REVIEW

**Comment by mum4k** [comment]
@tomjzzhang please review and assign back to me once done.

**Comment by tomjzzhang** [comment]
LGTM.

/retest.

**Review by tomjzzhang — APPROVED** [review]

**Pull request closed without merging**
