### PR TITLE
Update Envoy to 8188e232a9e0b15111d30f4724cbc7bf77d3964a

### PR DESCRIPTION
**Pull request by oschaaf**
List of changes:

- Update Envoy to 8188e232a9e0b15111d30f4724cbc7bf77d3964a (Dec 8th)
- Sync .bazelrc
- Modify extensions_build_config.bzl, add required DISABLED_BY_DEFAULT_EXTENSIONS
- Rework our h1 connection pool derivation to keep our own prefetching feature working.
   Note: We enable the allow_prefetch runtime feature for this.
- Changes to reflect changed Envoy constructors and method signatures: 
   OnPoolReady(), ProdClusterManagerFactory(), allocateConnPool() 
- Modified log filtering in the integration test: `SIGTERM` -> `ENVOY_SIGTERM`.
- Dropped include of `ares.h` as small cleanup, we no longer need that.
- In `options_impl.cc` there's a small change to how we define `elapsed_since_epoch` to unbreak
   building with `libc++`: a regression of https://github.com/envoyproxy/nighthawk/issues/569.
   Filed https://github.com/envoyproxy/nighthawk/issues/594 to avoid regression.

Signed-off-by: Otto van der Schaaf <oschaaf@we-amp.com>

----

Depends on:

- [x] Landing #575 
- [x] Fix broken ASAN CI run -> punted to https://github.com/envoyproxy/nighthawk/issues/593

### CODE REVIEW

**Comment by oschaaf** [comment]
So this now passes all tests, but asan has a structural build problem (it's not a flake):

```
ld.lld: error: undefined symbol: __muloti4
>>> referenced by int128_have_intrinsic.inc:251 (external/com_google_absl/absl/numeric/int128_have_intrinsic.inc:251)
>>>               bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/_objs/strings/numbers.pic.o:(absl::operator*(absl::int128, absl::int128))
```

Looking into that.

**Comment by mum4k** [comment]
@qqustc please review and assign back to me once done.

**Review by qqustc — APPROVED** [review]
Thanks Otto

**Comment by qqustc** [comment]
> @qqustc please review and assign back to me once done.

LGTM. Assign back to @mum4k

**Comment by mum4k** [comment]
@oschaaf I am assuming this still needs some work due to the failing CI. Please reapply the `waiting-for-review` label once this is ready.

**Comment by oschaaf** [comment]
To unblock this, I deferred the issue with CI/asan to #593. Marking this is ready for review again.

**Review by mum4k — APPROVED** [review]
Thank you @oschaaf.

**Pull request merged**
