### PR TITLE
Make benchmark duration env configurable for dynamic tests.

### PR DESCRIPTION
**Pull request by KBaichoo**
Signed-off-by: Kevin Baichoo <kbaichoo@google.com>

### CODE REVIEW

**Review by tomjzzhang — APPROVED** [review]
LGTM. I'm guessing the CI pipeline python failures are unrelated.

**Comment by tomjzzhang** [comment]
https://github.com/envoyproxy/nighthawk/pull/934/ should resolve your CI errors once merged.

**Comment by KBaichoo** [comment]
thanks @tomjzzhang  merged main 🤞

**Review by dubious90 — APPROVED** [review]

**Pull request merged**
