### PR TITLE
Update Envoy to 5183dbf (Aug 26th 2021)

### PR DESCRIPTION
**Pull request by fei-deng**
- update nighthawk to envoy commit `5183dbf7f11b23f1f7013a3e42cbce71eb63252a`.
- copied `.bazelrc` from Envoy.
- Removed unnecessary `well_know_protos` which caused a build error:

```
no such target '@com_google_protobuf//:well_known_type_protos':
target 'well_known_type_protos' not declared in package ''
defined by .../external/com_google_protobuf/BUILD and referenced by
'//api/request_source:_grpc_request_source_service_lib_grpc_codegen'.
```

### CODE REVIEW

**Review by mum4k — CHANGES_REQUESTED** [review]
@fei-deng could you please verify that all steps in the [maintenance procedure](https://github.com/envoyproxy/nighthawk/blob/main/MAINTAINERS.md#updates-to-the-envoy-dependency) were followed.

Looks like the [.bazelrc](https://github.com/envoyproxy/envoy/blob/main/.bazelrc) in Envoy was modified 6 days ago, so we should sync it. There could be other files similarly modified that the procedure mentions as well.

**Comment by fei-deng** [comment]
> @fei-deng could you please verify that all steps in the [maintenance procedure](https://github.com/envoyproxy/nighthawk/blob/main/MAINTAINERS.md#updates-to-the-envoy-dependency) were followed.
> 
> Looks like the [.bazelrc](https://github.com/envoyproxy/envoy/blob/main/.bazelrc) in Envoy was modified 6 days ago, so we should sync it. There could be other files similarly modified that the procedure mentions as well.

Thanks! Went through the list and updated accordingly.

**Comment by mum4k** [comment]
@eric846 please review and assign back to me once done.

**Review by mum4k — APPROVED** [review]

**Review by eric846 — APPROVED** [review]
LGTM

**Pull request merged**
