### PR TITLE
Envoy update to 29c2a5c (Aug 28th 2023)

### PR DESCRIPTION
**Pull request by jiajunye**
- No changes to `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh`, `tools/gen_compilation_database.py`.
- Synced changes from `tools/code_format/config.yaml`.
- Updated python dependencies in `requirements.txt`.

Signed-off-by: jiajunye [jiajunye@google.com](mailto:jiajunye@google.com)

### CODE REVIEW

**Comment by jiajunye** [comment]
retest/

**Comment by jiajunye** [comment]
\retest

**Review by eric846 — APPROVED** [review]
LGTM

**Pull request merged**
