### PR TITLE
Update Envoy to 8004b60 (Aug 13th 2023).

### PR DESCRIPTION
**Pull request by mum4k**
- synced `.bazelrc`, `.bazelversion`, `ci/run_envoy_docker.sh`,
  `tools/code_format/config.yaml` from Envoy's version.
- note: removed a `.bazelrc` line marked as `# unique` that used to set the `CC_CODE_COVERAGE_SCRIPT` variable It was unique, because path to the coverage script was different from our perspective. Removed it, because the code coverage tooling no longer uses the custom script since  https://github.com/envoyproxy/envoy/commit/8004b60fc9902f65b58c4a9153eb065d1a4152dc.
- setting `--test_timeout=900` for coverage as it seems to be taking longer with the new coverage script Envoy switched to.
- no changes to `.bazelversion`, `tools/gen_compilation_database.py`.
- adding dependency on `@envoy//envoy/common:base_includes` explicitly as the
  implicit one was removed in
  https://github.com/envoyproxy/envoy/commit/3f13f3e47087249121ad00d41308c8af6aa9204b.

### CODE REVIEW

**Comment by mum4k** [comment]
@chipmunkie please review and assign to @eric846 once done.

**Comment by mum4k** [comment]
@chipmunkie this is now passing CI and ready for review. Please assign to @eric846 once done.

**Review by chipmunkie — APPROVED** [review]
LGTM

**Review by eric846 — APPROVED** [review]
LGTM

**Pull request merged**
