### PR TITLE
Update Envoy to fb61801 (May 22nd 2023)

### PR DESCRIPTION
**Pull request by jiajunye**
- Sync `.bazelrc`, `ci/run_envoy_docker.sh` and `tools/code_format/config.yaml` from the Envoy repository.
- No changes to `.bazelversion` and `tools/gen_compilation_database.py`.
- Update `requirements.txt`.
- Fix `ModuleNotFoundError` when running benchmark framework with own binaries caused by https://github.com/envoyproxy/envoy/pull/25359.

Signed-off-by: jiajunye [jiajunye@google.com](mailto:jiajunye@google.com)

### CODE REVIEW

**Comment by jiajunye** [comment]
retest/

**Review by mum4k — APPROVED** [review]

**Pull request merged**
