### PR TITLE
Fix namespace dereferencing according to the style guide

### PR DESCRIPTION
**Pull request by oschaaf**
Just cleanup, no functional changes.

Closes https://github.com/envoyproxy/nighthawk/issues/652

Signed-off-by: Otto van der Schaaf <ovanders@redhat.com>

### CODE REVIEW

**Comment by oschaaf** [comment]
This does introduce a bit of code churn, if anyone anticipates having to deal with merge conflicts because of this, it's probably better to postpone this, please comment in that case.

**Comment by dubious90** [comment]
Hey Otto, just to confirm - is this currently blocked by https://github.com/envoyproxy/nighthawk/pull/647?

**Review by dubious90 — APPROVED** [review]
Approved, but blocked by #647

**Comment by oschaaf** [comment]
> Approved, but blocked by #647

I don't think this needs to be blocked on that, this is based on the main branch.

**Comment by oschaaf** [comment]
Backed out `test/distributor/nighthawk_distributor_client_test.cc`. Thanks @dubious90 for spelling it out on Slack, totally missed that.

**Review by dubious90 — APPROVED** [review]
Looks good now.

**Pull request merged**
