### PR TITLE
Some typo fixes

### PR DESCRIPTION
**Pull request by tomjzzhang**
Signed-off-by: tomjzzhang <4367421+tomjzzhang@users.noreply.github.com>

### CODE REVIEW

**Comment by tomjzzhang** [comment]
This PR serves two purposes. One is just some good cleanup. Two is to establish a baseline of integration test flakiness.

**Comment by mum4k** [comment]
@tomjzzhang looks like this may be the PR where you are experimenting with CI. I am converting it to draft until it is ready for a review, however do let me know if I misunderstood.

**Comment by tomjzzhang** [comment]
Done testing integration test flakiness. In its current state, the tests are failing ~70 ± ~10% with 95% level confidence.

**Review by mum4k — CHANGES_REQUESTED** [review]
Looks like this PR is doing more than just fixing some typos. Can we update its description to reflect what is being done here, or revert the other changes? Maybe we need to merge in the main?

**Comment by tomjzzhang** [comment]
> 

Sorry I thought I rebased correctly, but guess I'm doing it incorrectly. Merged with main instead.

**Review by mum4k — APPROVED** [review]

**Pull request merged**
