### PR TITLE
Update Envoy to a96ebf (Feb 16th 2021)

### PR DESCRIPTION
**Pull request by dubious90**

### CODE REVIEW

**Comment by mum4k** [comment]
@dubious90 not sure if this is ready for review, or still in progress. Please let us know.

**Comment by mum4k** [comment]
@dubious90 indicated offline that this is ready for review.

**Review by mum4k — APPROVED** [review]
Looks good assuming no other changes were necessary.

**Review by oschaaf — APPROVED** [review]
LGTM

**Pull request merged**
