### PR TITLE
Clean up do_ci.sh

### PR DESCRIPTION
**Pull request by oschaaf**
- Experimentally remove one-offs to throttle paralellism
- Eliminate some code duplication

Signed-off-by: Otto van der Schaaf <oschaaf@we-amp.com>

### CODE REVIEW

**Comment by oschaaf** [comment]
(this will be a draft for a little while, as it needs some tests to be re-run a few times to get a sense of stability)

**Comment by oschaaf** [comment]
Respinning CI multiple times indicates that stability doesn't suffer from the increased parallelism. The sanitizer runs
didn't fail once, and while coverage did fail, it does that sometimes regardless of this change
(and OOM is no longer seems to happen, which was driving the reduced parallelism). 
So with this change we are able to make more effective use of CI resources by leveraging all vCPUs in all tasks, plus we clean up a little bit of duplicated code.

**Comment by mum4k** [comment]
@wjuan-AFK please review and assign back to me once done.

**Comment by wjuan-AFK** [comment]
LGTM

**Pull request merged**
