### PR TITLE
Updating repository paths in README under benchmarks.

### PR DESCRIPTION
**Pull request by mum4k**
Changing github repository paths from oschaaf to envoyproxy.

Signed-off-by: Jakub Sobon <mumak@google.com>

### CODE REVIEW

**Comment by mum4k** [comment]
@oschaaf there is also a reference to `oschaaf/benchmark-dev:latest` in the same readme. Is that the correct path for us to use?

**Review by oschaaf — APPROVED** [review]
Ah, yeah, good idea.

**Comment by mum4k** [comment]
@oschaaf please see my question about the reference to `oschaaf/benchmark-dev:latest` in the same file.

**Comment by oschaaf** [comment]
> @oschaaf there is also a reference to `oschaaf/benchmark-dev:latest` in the same readme. Is that the correct path for us to use?

Oh, sorry I missed that. I think that for the time being it's the best option, because we don't push the image in CI to a proper location. There's https://hub.docker.com/r/envoyproxy/nighthawk-dev, maybe we should try to also obtain https://hub.docker.com/r/envoyproxy/nighthawk-benchmark-dev (or some such) as a location to push to.

**Comment by oschaaf** [comment]
(Filed https://github.com/envoyproxy/nighthawk/issues/611 to track)

**Comment by mum4k** [comment]
Thank you @oschaaf!

**Pull request merged**
