### PR TITLE
Update Envoy to 0546512 (Sep 06, 2023)

### PR DESCRIPTION
**Pull request by eric846**
- Updated `.bazelrc`
- Updated `.bazelversion`
- Updated `ci/run_envoy_docker.sh`
- Adapted to the deletion of `SingletonLoader` in https://github.com/envoyproxy/envoy/commit/a96e0f0c2d504a1a0f1780779e9f7cd1b8ad6ae6. Now we just create a `Loader` and control its lifetime as a `unique_ptr` field in the Nighthawk `Process` object, of which only one should exist at a time.
- Regenerated Test Server docs (capitalization and punctuation changes only)
- Adopted the new Bazelified format check (https://github.com/envoyproxy/envoy/pull/29397): `bazel run //tools/code_format:check_format.py` changed to `bazel run //tools/code_format:check_format`
- Decreased RPS 2x in built-in benchmark suite to deflake the CI. It previously failed 2 out of 3 times on this PR.

### CODE REVIEW

**Comment by eric846** [comment]
Noting that I had to rerun the CI twice before the benchmark passed.

**Comment by mum4k** [comment]
@qqustc please review and assign to @eric846 once done.

**Review by qqustc — APPROVED** [review]

**Pull request merged**
