### PR TITLE
Update Envoy & HdrHistogram_c

### PR DESCRIPTION
**Pull request by oschaaf**
- Update Envoy to 2097fe908f2abb718757dbd4087d793c861d7c5a
- Update HdrHistogram_c to 0.11.2

Adds `--define tcmalloc=gperftools` to the opt build we use to push images,
to (continue to) allow cpu profiling. We need this because of https://github.com/envoyproxy/envoy/commit/4c0d2d2a36996f2ec7d00b519ea90068629a2c55

Signed-off-by: Otto van der Schaaf <oschaaf@we-amp.com>

### CODE REVIEW

**Review by dubious90 — APPROVED** [review]

**Comment by dubious90** [comment]
Can you resolve the clang tidy failure, and then re-apply the waiting-for-review label?

**Comment by oschaaf** [comment]
@dubious90 a128bfe addresses the clang tidy issue here. In this PR, that task started to structurally fail without showing an actual complaint (it started flaking earlier, which is tracked in #546).
I copied over changes from Envoy's version of the clang tidy check script to our own, and after doing so an actual complaint emerged that I addressed. As a side effect, I suspect #546 will also be resolved upon merging this.

**Review by dubious90 — APPROVED** [review]

**Comment by oschaaf** [comment]
@dubious90 sorry - with dd0e19834dd117b2769f5420794adbf761f1e580, which resolves a last quotation issue this now passes. I'd like to retry a few times to see if this also deflakes the clang-tidy task in CI, I'll ping you on Slack once I know more about that.

**Comment by oschaaf** [comment]
@dubious90 unfortunately, this doesn't resolve the clang-tidy flakes, though it is an enhancement and now passes again some of the time instead of structurally failing. resolving #546 needs more looking into.

**Review by dubious90 — APPROVED** [review]

**Pull request merged**
