### PR TITLE
Update Envoy to ad9434b (Mar 21st 2022)

### PR DESCRIPTION
**Pull request by jiajunye**
- Update the `ENVOY_COMMIT` and `ENVOY_SHA` in [bazel/repositories.bzl](https://github.com/envoyproxy/nighthawk/blob/main/bazel/repositories.bzl) to the latest Envoy's commit.
- Sync [.bazelrc](https://github.com/envoyproxy/nighthawk/blob/main/.bazelrc) from Envoy's version to update our build configurations.
- Update `envoyproxy/envoy-build-ubuntu` over at the top of [.circleci/config.yml](https://github.com/envoyproxy/nighthawk/blob/main/.circleci/config.yml) with the new SHA in the `experimental_docker_image` in [.bazelrc](https://github.com/envoyproxy/nighthawk/blob/main/.bazelrc).
- Update the `allocateConnPool()` overriding in `process_impl.cc` to accommodate the changes in `cluster_manager_impl` by https://github.com/envoyproxy/envoy/commit/d63c423be9dfbf191955dda51cda8803837c2395
- Update the `percentile-column-overflow.txt.gold` to pass the `output_formatter_test`. It was failed with the error:

```
test/output_formatter_test.cc:84: Failure
 Expected equality of these values:
   s
     Which is: "Nighthawk - A layer 7 protocol benchmarking tool.\n\nfoo (1 samples)\n  m
   output
     Which is: "Nighthawk - A layer 7 protocol benchmarking tool.\n\nfoo (1 samples)\n  m
 With diff:
 @@ -2,5 +2,5 @@
 
  foo (1 samples)
 -  min: 0 | mean: 0.0 | max: 0 | pstdev: 0.0
 +  min: 0 | mean: 0 | max: 0 | pstdev: 0
```

-  Update README.md by executing `tools/update_cli_readme_documentation.sh --mode fix`

-  Add `--assert=plain pytest` argument to `benchmarks.py` as a workaround to resolve the failure of `benchmark_with_own_binaries` which is related to https://github.com/envoyproxy/nighthawk/issues/819

Signed-off-by: jiajunye [jiajunye@google.com](mailto:jiajunye@google.com)

### CODE REVIEW

**Comment by jiajunye** [comment]
@mum4k I tried to /retest failed tests. However, they failed with `500 Server Error`. See previous comments. Is this related to https://github.com/envoyproxy/nighthawk/issues/820? My local `ci/do_ci.sh test` succeeded.

**Review by mum4k — APPROVED** [review]

**Review by mum4k — CHANGES_REQUESTED** [review]
The `build` failure indicates that we need to update README.md, can you run the following?

`tools/update_cli_readme_documentation.sh --mode fix`

We can ignore the `integration_test_coverage` failure which is due to #820.

The failure of `benchmark_with_own_binaries` seems to be related to #819. Can you add the same workaround (the `--assert=plain` pytest argument) Eric added in #817? I think the argument needs to be inserted here:

https://github.com/envoyproxy/nighthawk/blob/c2321153b0a5f7070501249c7b9dde4a8f431fc2/benchmarks/benchmarks.py#L13

**Comment by jiajunye** [comment]
`ci/circleci: format` is showing pending. However, if you click through the `Details`, it shows success.

**Review by mum4k — APPROVED** [review]
Thank you @jiajunye, looks good and I have confirmed the integration tests pass locally.

**Pull request merged**
