### PR TITLE
Update Envoy to 9fc5535 (Apr 26, 2024)

### PR DESCRIPTION
**Pull request by eric846**
- Forced to set `StreamInfoImpl` lifespan explicitly after https://github.com/envoyproxy/envoy/commit/953690a26f20137607ac331fd0232da86f41fcea
  -   `FilterState::LifeSpan life_span = FilterState::LifeSpan::FilterChain` was the default we had been using: https://github.com/envoyproxy/envoy/pull/33651/files#diff-621e35bff59bda73d45b8171cab02f360f77bb948d2797936090e5afaee73020

### CODE REVIEW

**Comment by mum4k** [comment]
@jiajunye please review and assign to me once done.

**Comment by mum4k** [comment]
Actually just noticed this is still a Draft. Please hold on until @eric846 finishes working on it.

**Comment by eric846** [comment]
@jiajunye Please review and assign to me once done.

**Comment by jiajunye** [comment]
LGTM

**Comment by eric846** [comment]
@jiajunye could you also mark "Approved"?

**Review by mum4k — APPROVED** [review]

**Pull request merged**
