### PR TITLE
A collection of fixes that simplify import of Nighthawk into Google.

### PR DESCRIPTION
**Pull request by mum4k**
Done here:

- exporting the main LICENSES file.
- not referring to Nighthawk's code as if it was external.
- fixing bad include prefix and import of Nighthawk's distributor API.
- removing implicit conversions of strings to booleans.

### CODE REVIEW

**Comment by mum4k** [comment]
@tomjzzhang sorry had to close #779 since I damaged my branch. Here is a clone, but with less changes. We are no longer removing the comments next to the license statements.

PTAL

**Review by tomjzzhang — APPROVED** [review]
LGTM

**Review by dubious90 — APPROVED** [review]

**Pull request merged**
